config/routes.rb
Treebook::Application.routes.draw do
  
  get "profiles/show"
  root :to => "statuses#index"

  devise_for :users
  get "/:id", to: "profiles#show"


	devise_scope :user do
		get "sign_up", to: "devise/registrations#new"
	  get "sign_in", to: "devise/sessions#new"	  
	  get "sign_out", to: "devise/sessions#destroy"
	end 

	resources :statuses

	get "feed", to: "statuses#index"	 
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :statuses 

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
  												 uniqueness: true
  												 # format: {
  												 # 	with: /a-zA-Z0-9_-/,
  												 # 	# message: 'Must be formatted correctly.'
  												 # }

  def full_name
  	first_name + " " +last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end 	 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:profile_name, :first_name, :last_name] 
    devise_parameter_sanitizer.for(:account_update) << [:profile_name, :first_name, :last_name]  
  end 

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  	else	
  		render file: 'public/404', status:404, formats: [:html]
		end  
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice	
			"alert-success"
		else
			""
		end
	end			
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
    	<div class="navbar navbar-inverse navbar-static-top">
  			<div class="navbar-header">
          <span class="navbar-brand">
            <%= link_to "Treebook", root_path %>
          </span>
  				<ul class="nav navbar-nav">
          	<li><%= link_to "All Statuses", feed_path %></li>
          </ul>	 
  			</div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log out", sign_out_path %></li>
          <% else %>
            <li><%= link_to "Sign up", sign_up_path %></li>
            <li><%= link_to "Login", sign_in_path %></li>
          <% end %>
        </ul> 
    	</div>
      <div class="container"> 
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type) %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= message %>
          </div>  
        <% end %>     
      </div>

      <div>
      	<%= yield %>
      </div>
      
    </div> <!-- end row -->
	</div> <!-- end container -->
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>	

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>		
<% end %>	

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All of the Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status|%>
<div class="status-row">
  <div class ="row">
    <div class="col-md-1">
      <%= image_tag status.user.gravatar_url %>
    </div>

    <div class="col-md-7">
      <p>
        <b><%= status.user.full_name %></b>
      </p>
      
      <p><%= status.content %></p>

      <div class="meta">
      <!-- The timestamps macro adds two columns, created_at and updated_at. -->
        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> |
          <%= link_to "Delete", status, method: :delete, data: { confirm: 'Are you sure you want to delete this status?' } %>
        </span>
      </div>
    </div>  
  </div>
</div>  
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
   <b><%= @status.user.full_name %></b>
</p>
<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>